In [1]:
from sklearn import datasets
import pandas as pd
from sklearn.neighbors import KNeighborsClassifier,KNeighborsRegressor
from sklearn.model_selection import train_test_split,cross_val_score,GridSearchCV
from sklearn.metrics import mean_squared_error
import matplotlib.pyplot as plt
import numpy as np
# from sklearn.linear_model import LinearRegression,LogisticRegression,Ridge,Lasso
# from sklearn.utils import shuffle
# from sklearn.preprocessing import StandardScaler
# from scipy.stats import mode
# from sklearn.cluster import KMeans
# from sklearn.manifold import TSNE
# from sklearn.decomposition import PCA
# from sklearn.pipeline import make_pipeline
# from sklearn.svm import LinearSVC,SVC,SVR,LinearSVR
# from sklearn.ensemble import RandomForestClassifier,RandomForestRegressor,VotingClassifier,GradientBoostingClassifier
# from sklearn.tree import DecisionTreeClassifier,DecisionTreeRegressor
# from keras.models import Sequential
# from keras.layers import Dense
# from keras.utils import to_categorical
# from keras.callbacks import EarlyStopping
# powers = [1e-4,1e-3,1e-2,1e-1,1,1e1,1e2,1e3,1e4]
# zoomed = np.array(range(1,101))
# import random

In [2]:
boston = datasets.load_boston()

In [3]:
boston.keys()

dict_keys(['data', 'target', 'feature_names', 'DESCR', 'filename'])

In [4]:
print(boston['DESCR'])

.. _boston_dataset:

Boston house prices dataset
---------------------------

**Data Set Characteristics:**  

    :Number of Instances: 506 

    :Number of Attributes: 13 numeric/categorical predictive. Median Value (attribute 14) is usually the target.

    :Attribute Information (in order):
        - CRIM     per capita crime rate by town
        - ZN       proportion of residential land zoned for lots over 25,000 sq.ft.
        - INDUS    proportion of non-retail business acres per town
        - CHAS     Charles River dummy variable (= 1 if tract bounds river; 0 otherwise)
        - NOX      nitric oxides concentration (parts per 10 million)
        - RM       average number of rooms per dwelling
        - AGE      proportion of owner-occupied units built prior to 1940
        - DIS      weighted distances to five Boston employment centres
        - RAD      index of accessibility to radial highways
        - TAX      full-value property-tax rate per $10,000
        - PTRATIO  pu

In [5]:
boston['data']

array([[6.3200e-03, 1.8000e+01, 2.3100e+00, ..., 1.5300e+01, 3.9690e+02,
        4.9800e+00],
       [2.7310e-02, 0.0000e+00, 7.0700e+00, ..., 1.7800e+01, 3.9690e+02,
        9.1400e+00],
       [2.7290e-02, 0.0000e+00, 7.0700e+00, ..., 1.7800e+01, 3.9283e+02,
        4.0300e+00],
       ...,
       [6.0760e-02, 0.0000e+00, 1.1930e+01, ..., 2.1000e+01, 3.9690e+02,
        5.6400e+00],
       [1.0959e-01, 0.0000e+00, 1.1930e+01, ..., 2.1000e+01, 3.9345e+02,
        6.4800e+00],
       [4.7410e-02, 0.0000e+00, 1.1930e+01, ..., 2.1000e+01, 3.9690e+02,
        7.8800e+00]])

In [6]:
boston['target']

array([24. , 21.6, 34.7, 33.4, 36.2, 28.7, 22.9, 27.1, 16.5, 18.9, 15. ,
       18.9, 21.7, 20.4, 18.2, 19.9, 23.1, 17.5, 20.2, 18.2, 13.6, 19.6,
       15.2, 14.5, 15.6, 13.9, 16.6, 14.8, 18.4, 21. , 12.7, 14.5, 13.2,
       13.1, 13.5, 18.9, 20. , 21. , 24.7, 30.8, 34.9, 26.6, 25.3, 24.7,
       21.2, 19.3, 20. , 16.6, 14.4, 19.4, 19.7, 20.5, 25. , 23.4, 18.9,
       35.4, 24.7, 31.6, 23.3, 19.6, 18.7, 16. , 22.2, 25. , 33. , 23.5,
       19.4, 22. , 17.4, 20.9, 24.2, 21.7, 22.8, 23.4, 24.1, 21.4, 20. ,
       20.8, 21.2, 20.3, 28. , 23.9, 24.8, 22.9, 23.9, 26.6, 22.5, 22.2,
       23.6, 28.7, 22.6, 22. , 22.9, 25. , 20.6, 28.4, 21.4, 38.7, 43.8,
       33.2, 27.5, 26.5, 18.6, 19.3, 20.1, 19.5, 19.5, 20.4, 19.8, 19.4,
       21.7, 22.8, 18.8, 18.7, 18.5, 18.3, 21.2, 19.2, 20.4, 19.3, 22. ,
       20.3, 20.5, 17.3, 18.8, 21.4, 15.7, 16.2, 18. , 14.3, 19.2, 19.6,
       23. , 18.4, 15.6, 18.1, 17.4, 17.1, 13.3, 17.8, 14. , 14.4, 13.4,
       15.6, 11.8, 13.8, 15.6, 14.6, 17.8, 15.4, 21

In [7]:
boston['target'].shape

(506,)

In [8]:
boston['feature_names']

array(['CRIM', 'ZN', 'INDUS', 'CHAS', 'NOX', 'RM', 'AGE', 'DIS', 'RAD',
       'TAX', 'PTRATIO', 'B', 'LSTAT'], dtype='<U7')

In [9]:
x = pd.DataFrame(boston['data'],columns=boston['feature_names'])
x.head(10)

CRIM    ZN  INDUS  CHAS    NOX     RM    AGE     DIS  RAD    TAX  \
0  0.00632  18.0   2.31   0.0  0.538  6.575   65.2  4.0900  1.0  296.0   
1  0.02731   0.0   7.07   0.0  0.469  6.421   78.9  4.9671  2.0  242.0   
2  0.02729   0.0   7.07   0.0  0.469  7.185   61.1  4.9671  2.0  242.0   
3  0.03237   0.0   2.18   0.0  0.458  6.998   45.8  6.0622  3.0  222.0   
4  0.06905   0.0   2.18   0.0  0.458  7.147   54.2  6.0622  3.0  222.0   
5  0.02985   0.0   2.18   0.0  0.458  6.430   58.7  6.0622  3.0  222.0   
6  0.08829  12.5   7.87   0.0  0.524  6.012   66.6  5.5605  5.0  311.0   
7  0.14455  12.5   7.87   0.0  0.524  6.172   96.1  5.9505  5.0  311.0   
8  0.21124  12.5   7.87   0.0  0.524  5.631  100.0  6.0821  5.0  311.0   
9  0.17004  12.5   7.87   0.0  0.524  6.004   85.9  6.5921  5.0  311.0   

   PTRATIO       B  LSTAT  
0     15.3  396.90   4.98  
1     17.8  396.90   9.14  
2     17.8  392.83   4.03  
3     18.7  394.63   2.94  
4     18.7  396.90   5.33  
5     18.7  394.12   5.21  
6     15.2  395.60  12.43  
7     15.2  396.90  19.15  
8     15.2  386.63  29.93  
9     15.2  386.71  17.10

In [10]:
y=boston.target

In [11]:
model=KNeighborsRegressor()

In [12]:
model.fit(x,y)

KNeighborsRegressor(algorithm='auto', leaf_size=30, metric='minkowski',
                    metric_params=None, n_jobs=None, n_neighbors=5, p=2,
                    weights='uniform')

In [13]:
model.score(x,y)

0.716098217736928

In [23]:
knn=KNeighborsRegressor()

In [39]:
x_train,x_test,y_train,y_test = train_test_split(x,y,
                                test_size=0.3,random_state=42)


In [40]:
knn.fit(x_train,y_train)

KNeighborsRegressor(algorithm='auto', leaf_size=30, metric='minkowski',
                    metric_params=None, n_jobs=None, n_neighbors=5, p=2,
                    weights='uniform')

In [41]:
model.score(x_test,y_test)

0.7725176977665994

In [42]:
model.score(x_train,y_train)

0.6930529970731816

In [55]:
model.predict(x_test)

array([24.4 , 31.96, 14.86, 27.76, 17.04, 25.82, 18.54, 15.24, 18.6 ,
       19.96, 21.1 , 19.48, 10.92, 21.38, 22.9 , 23.28, 19.66, 13.18,
       34.9 , 14.48, 28.82, 31.96, 14.1 , 21.18, 16.98, 15.54, 22.02,
       12.54, 21.1 , 18.7 , 21.9 , 23.32, 10.82, 30.94, 18.56, 20.24,
       25.36, 25.74, 22.9 , 27.76, 18.7 , 27.02, 41.28, 20.42, 25.58,
       13.52, 14.1 , 27.76, 20.24, 21.78, 22.  , 32.58, 18.3 , 22.2 ,
       32.42, 21.34, 13.84, 34.9 , 25.98, 19.68, 24.06, 39.82, 29.44,
       15.7 , 28.  , 21.1 , 13.54, 25.22, 31.88, 13.58, 20.44, 22.72,
       13.44, 24.8 , 21.64,  8.5 , 19.74, 41.28, 10.26, 11.54, 20.42,
       14.52, 24.86, 11.88, 21.02, 28.12, 14.34, 22.06, 26.04, 18.4 ,
       22.34, 14.58, 18.4 , 18.84, 27.22, 18.78, 36.6 , 11.88, 12.1 ,
       12.74, 23.28, 21.64, 14.96, 21.3 , 22.98, 13.58, 23.54, 23.76,
       20.78, 27.08, 10.56, 17.62, 21.16, 38.56, 35.96, 12.9 , 33.24,
       15.1 , 22.08, 21.44, 20.  , 31.22, 11.96, 20.1 , 25.36, 23.32,
       26.48, 33.24,

In [56]:
model.predict(x_train)

array([27.1 , 20.2 , 20.44, 30.48, 23.7 , 33.8 , 26.06,  6.86, 38.56,
       21.78, 22.08, 23.76, 34.6 , 18.34, 41.88, 15.88, 16.78, 19.1 ,
       18.3 , 19.66, 27.4 , 37.78, 22.72, 20.66, 20.1 , 25.82, 33.72,
       31.74, 15.62, 11.36, 11.62, 15.88, 31.96, 25.42, 13.58, 14.76,
       39.16, 22.18, 25.6 , 19.98, 18.7 , 11.74,  9.54, 31.8 , 31.22,
       19.56, 16.98, 18.26, 26.34, 19.28, 31.8 , 31.22, 25.64, 21.38,
       20.24, 44.54, 29.38, 41.28, 22.92, 21.32, 12.2 , 31.22, 19.8 ,
       24.84, 28.02, 20.86, 19.06, 10.5 , 29.5 , 41.88, 34.12,  8.94,
       14.18, 22.14, 26.78, 17.06, 39.16, 20.  , 21.88,  9.6 , 25.64,
       20.1 , 25.58, 38.82, 20.88, 27.22, 20.88, 24.44, 25.52, 37.22,
       24.2 , 12.46, 33.24, 20.5 , 19.28, 14.16, 19.74, 21.88, 28.44,
       19.52, 19.52, 16.06, 29.12, 23.22, 26.78, 12.5 , 18.26, 13.98,
       15.62, 13.52, 22.62, 18.52, 12.28, 23.62, 15.62, 21.92, 31.96,
       24.32, 42.8 , 19.66, 31.6 , 25.3 , 22.16, 22.8 , 25.78, 20.96,
       10.34, 14.82,

In [53]:
model.predict(x_test).shape  

(152,)

In [52]:
model.predict(x_train).shape

(354,)