In [90]:
from sklearn import datasets
import pandas as pd
from sklearn.neighbors import KNeighborsClassifier,KNeighborsRegressor
from sklearn.model_selection import train_test_split,cross_val_score,GridSearchCV
from sklearn.metrics import mean_squared_error
import matplotlib.pyplot as plt
import numpy as np
from sklearn.linear_model import LinearRegression,LogisticRegression,Ridge,Lasso
from sklearn.utils import shuffle
from sklearn.preprocessing import StandardScaler
powers = [1e-4,1e-3,1e-2,1e-1,1,1e1,1e2,1e3,1e4]
zoomed = np.array(range(1,101))

In [91]:
digits=datasets.load_digits()

In [92]:
digits.keys()

dict_keys(['data', 'target', 'target_names', 'images', 'DESCR'])

In [93]:
print(digits['DESCR'])

.. _digits_dataset:

Optical recognition of handwritten digits dataset
--------------------------------------------------

**Data Set Characteristics:**

    :Number of Instances: 5620
    :Number of Attributes: 64
    :Attribute Information: 8x8 image of integer pixels in the range 0..16.
    :Missing Attribute Values: None
    :Creator: E. Alpaydin (alpaydin '@' boun.edu.tr)
    :Date: July; 1998

This is a copy of the test set of the UCI ML hand-written digits datasets
http://archive.ics.uci.edu/ml/datasets/Optical+Recognition+of+Handwritten+Digits

The data set contains images of hand-written digits: 10 classes where
each class refers to a digit.

Preprocessing programs made available by NIST were used to extract
normalized bitmaps of handwritten digits from a preprinted form. From a
total of 43 people, 30 contributed to the training set and different 13
to the test set. 32x32 bitmaps are divided into nonoverlapping blocks of
4x4 and the number of on pixels are counted in each bloc

In [94]:
digits.data

array([[ 0.,  0.,  5., ...,  0.,  0.,  0.],
       [ 0.,  0.,  0., ..., 10.,  0.,  0.],
       [ 0.,  0.,  0., ..., 16.,  9.,  0.],
       ...,
       [ 0.,  0.,  1., ...,  6.,  0.,  0.],
       [ 0.,  0.,  2., ..., 12.,  0.,  0.],
       [ 0.,  0., 10., ..., 12.,  1.,  0.]])

In [95]:
digits['data']

array([[ 0.,  0.,  5., ...,  0.,  0.,  0.],
       [ 0.,  0.,  0., ..., 10.,  0.,  0.],
       [ 0.,  0.,  0., ..., 16.,  9.,  0.],
       ...,
       [ 0.,  0.,  1., ...,  6.,  0.,  0.],
       [ 0.,  0.,  2., ..., 12.,  0.,  0.],
       [ 0.,  0., 10., ..., 12.,  1.,  0.]])

In [96]:
digits['target']

array([0, 1, 2, ..., 8, 9, 8])

In [97]:
digits.target

array([0, 1, 2, ..., 8, 9, 8])

In [98]:
digits['target_names']

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [99]:
digits['images']

array([[[ 0.,  0.,  5., ...,  1.,  0.,  0.],
        [ 0.,  0., 13., ..., 15.,  5.,  0.],
        [ 0.,  3., 15., ..., 11.,  8.,  0.],
        ...,
        [ 0.,  4., 11., ..., 12.,  7.,  0.],
        [ 0.,  2., 14., ..., 12.,  0.,  0.],
        [ 0.,  0.,  6., ...,  0.,  0.,  0.]],

       [[ 0.,  0.,  0., ...,  5.,  0.,  0.],
        [ 0.,  0.,  0., ...,  9.,  0.,  0.],
        [ 0.,  0.,  3., ...,  6.,  0.,  0.],
        ...,
        [ 0.,  0.,  1., ...,  6.,  0.,  0.],
        [ 0.,  0.,  1., ...,  6.,  0.,  0.],
        [ 0.,  0.,  0., ..., 10.,  0.,  0.]],

       [[ 0.,  0.,  0., ..., 12.,  0.,  0.],
        [ 0.,  0.,  3., ..., 14.,  0.,  0.],
        [ 0.,  0.,  8., ..., 16.,  0.,  0.],
        ...,
        [ 0.,  9., 16., ...,  0.,  0.,  0.],
        [ 0.,  3., 13., ..., 11.,  5.,  0.],
        [ 0.,  0.,  0., ..., 16.,  9.,  0.]],

       ...,

       [[ 0.,  0.,  1., ...,  1.,  0.,  0.],
        [ 0.,  0., 13., ...,  2.,  1.,  0.],
        [ 0.,  0., 16., ..., 16.,  5.,  0.

In [100]:
knn=KNeighborsClassifier()

In [101]:
X,y = digits.data,digits.target

In [102]:
knn.fit(X,y)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=None, n_neighbors=5, p=2,
           weights='uniform')

In [103]:
knn.predict(X)

array([0, 1, 2, ..., 8, 9, 8])

In [104]:
y

array([0, 1, 2, ..., 8, 9, 8])

In [105]:
knn.score(X,y)

0.9905397885364496

In [106]:
X_train,X_test,y_train,y_test=train_test_split(X,y,random_state=42,test_size=0.3,stratify=y)

In [107]:
knn.fit(X_train,y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=None, n_neighbors=5, p=2,
           weights='uniform')

In [108]:
knn.score(X_train,y_train)

0.9920445505171042

In [109]:
knn.score(X_test,y_test)

0.987037037037037

In [110]:
knn.predict(X_test)

array([1, 3, 1, 5, 0, 6, 6, 7, 4, 9, 3, 9, 7, 7, 6, 1, 5, 7, 3, 3, 9, 8,
       5, 5, 4, 4, 9, 3, 2, 3, 6, 0, 2, 0, 4, 6, 1, 8, 5, 5, 2, 3, 1, 3,
       2, 6, 5, 8, 9, 6, 0, 4, 6, 5, 1, 6, 6, 6, 2, 3, 1, 2, 9, 9, 4, 6,
       1, 5, 0, 9, 9, 8, 4, 7, 7, 9, 0, 0, 4, 9, 5, 4, 1, 9, 0, 0, 5, 6,
       5, 7, 3, 5, 3, 1, 5, 9, 2, 3, 9, 7, 4, 0, 0, 9, 2, 7, 3, 1, 4, 9,
       3, 8, 2, 5, 1, 1, 6, 9, 4, 3, 7, 1, 8, 1, 9, 7, 9, 0, 3, 2, 7, 7,
       2, 4, 0, 8, 4, 1, 5, 7, 2, 4, 2, 9, 5, 9, 5, 4, 4, 2, 0, 3, 3, 7,
       2, 5, 1, 5, 1, 0, 6, 7, 7, 3, 2, 3, 1, 0, 7, 3, 0, 7, 4, 9, 2, 5,
       3, 0, 0, 9, 5, 1, 7, 6, 5, 3, 4, 6, 0, 6, 6, 3, 4, 6, 2, 1, 6, 9,
       7, 4, 3, 4, 2, 4, 8, 0, 3, 1, 2, 4, 7, 2, 0, 8, 8, 6, 1, 8, 4, 5,
       1, 0, 2, 8, 4, 2, 0, 1, 6, 8, 3, 5, 8, 3, 1, 9, 0, 4, 6, 2, 8, 6,
       7, 1, 0, 4, 6, 0, 8, 2, 8, 9, 1, 2, 3, 9, 4, 7, 5, 7, 2, 9, 4, 6,
       2, 8, 7, 5, 8, 8, 0, 3, 2, 3, 1, 2, 6, 8, 5, 2, 8, 3, 1, 3, 0, 5,
       3, 1, 7, 2, 0, 1, 0, 9, 7, 9, 2, 3, 5, 3, 0,

In [111]:
y_test

array([1, 3, 1, 5, 0, 6, 6, 7, 4, 9, 3, 9, 7, 7, 6, 1, 5, 7, 3, 3, 9, 8,
       5, 5, 4, 4, 9, 3, 2, 3, 6, 0, 2, 0, 4, 6, 1, 8, 5, 5, 2, 3, 1, 3,
       2, 6, 5, 8, 9, 6, 0, 4, 6, 5, 1, 6, 6, 6, 2, 3, 1, 2, 9, 9, 4, 6,
       1, 5, 0, 9, 9, 8, 4, 7, 7, 5, 0, 0, 4, 9, 5, 4, 1, 9, 0, 0, 5, 6,
       5, 7, 3, 5, 3, 1, 5, 9, 2, 3, 9, 7, 4, 0, 0, 9, 2, 7, 3, 1, 4, 9,
       3, 8, 2, 5, 1, 1, 6, 9, 4, 3, 7, 1, 8, 1, 9, 7, 9, 0, 3, 2, 7, 7,
       2, 4, 0, 8, 4, 8, 5, 7, 2, 4, 2, 9, 5, 9, 5, 4, 4, 2, 0, 3, 3, 7,
       2, 5, 1, 5, 1, 0, 6, 7, 7, 3, 2, 3, 1, 0, 7, 3, 0, 7, 4, 9, 2, 5,
       3, 0, 0, 9, 5, 1, 7, 6, 5, 3, 4, 6, 0, 6, 6, 3, 4, 6, 2, 1, 6, 9,
       7, 4, 3, 4, 2, 4, 8, 0, 3, 1, 2, 4, 7, 2, 0, 8, 8, 6, 1, 8, 4, 5,
       1, 0, 2, 8, 4, 2, 0, 1, 6, 8, 8, 5, 8, 3, 1, 9, 0, 4, 6, 2, 9, 6,
       7, 1, 0, 4, 6, 0, 8, 2, 8, 9, 1, 2, 3, 9, 4, 7, 5, 7, 2, 9, 4, 6,
       2, 8, 7, 5, 8, 8, 0, 3, 2, 3, 1, 2, 6, 8, 5, 2, 8, 3, 1, 3, 0, 5,
       3, 1, 7, 2, 0, 1, 0, 9, 7, 9, 2, 3, 5, 3, 0,

In [112]:
X_shuffle,y_shuffle = shuffle(X,y,random_state=42)
cross_val_score(KNeighborsClassifier(),X_shuffle,y_shuffle,cv=5,n_jobs=-1)

array([0.98901099, 0.99171271, 0.97214485, 0.99439776, 0.98309859])

In [113]:
np.mean(cross_val_score(KNeighborsClassifier(),X_shuffle,y_shuffle,cv=11,n_jobs=-1))

0.9865887204665605

In [114]:
model=LogisticRegression()

In [115]:
X,y=digits.data,digits.target

In [116]:
model.fit(X,y)

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:460: FutureWarning: Default multi_class will be changed to 'auto' in 0.22. Specify the multi_class option to silence this warning.
  "this warning.", FutureWarning)


LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='warn',
          n_jobs=None, penalty='l2', random_state=None, solver='warn',
          tol=0.0001, verbose=0, warm_start=False)

In [117]:
model.score(X,y)

0.993322203672788

In [118]:
model.predict(X)

array([0, 1, 2, ..., 8, 9, 8])

In [119]:
    y

array([0, 1, 2, ..., 8, 9, 8])

In [120]:
X_train,X_train,y_test,y_test=train_test_split(X,y,random_state=42,test_size=0.3,stratify=y)

In [123]:
model.fit(X_train,y_train)


C:\ProgramData\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


ValueError: Found input variables with inconsistent numbers of samples: [540, 1257]

In [122]:

model.score(X_test,y_test)

0.9907407407407407

In [87]:
model.predict(X_test)

array([1, 3, 1, 5, 0, 6, 6, 7, 4, 9, 3, 9, 7, 7, 6, 1, 5, 7, 3, 3, 9, 8,
       5, 5, 4, 4, 9, 3, 2, 3, 6, 0, 2, 0, 4, 6, 1, 8, 5, 5, 2, 3, 1, 3,
       2, 6, 5, 8, 8, 6, 0, 4, 6, 5, 1, 6, 6, 6, 2, 3, 1, 2, 9, 9, 4, 6,
       1, 5, 0, 9, 9, 8, 4, 7, 7, 5, 0, 0, 4, 9, 5, 4, 1, 9, 0, 0, 5, 6,
       5, 7, 3, 5, 3, 1, 5, 9, 2, 3, 9, 7, 4, 0, 0, 9, 2, 7, 3, 1, 4, 9,
       3, 8, 2, 5, 1, 8, 6, 9, 4, 3, 7, 1, 8, 1, 9, 7, 9, 0, 3, 2, 7, 7,
       2, 4, 0, 8, 4, 1, 5, 7, 2, 4, 2, 9, 5, 9, 5, 4, 4, 2, 0, 3, 3, 7,
       2, 5, 1, 5, 1, 0, 6, 7, 7, 3, 2, 3, 1, 0, 7, 3, 0, 7, 4, 9, 2, 5,
       3, 0, 0, 9, 5, 1, 7, 6, 5, 3, 4, 6, 0, 6, 6, 3, 4, 6, 2, 1, 6, 9,
       7, 4, 3, 4, 2, 4, 8, 0, 3, 1, 2, 4, 7, 2, 0, 8, 8, 6, 1, 8, 4, 5,
       1, 0, 2, 8, 4, 2, 0, 1, 6, 8, 8, 5, 8, 3, 1, 9, 0, 4, 6, 2, 9, 6,
       7, 1, 0, 4, 6, 0, 8, 2, 8, 9, 1, 2, 3, 9, 4, 7, 5, 7, 2, 9, 4, 6,
       2, 8, 7, 5, 8, 8, 0, 3, 2, 3, 1, 2, 6, 8, 5, 2, 8, 3, 1, 3, 0, 5,
       3, 1, 7, 2, 0, 1, 0, 9, 7, 9, 2, 3, 5, 3, 0,

In [74]:
y_test

array([1, 3, 1, 5, 0, 6, 6, 7, 4, 9, 3, 9, 7, 7, 6, 1, 5, 7, 3, 3, 9, 8,
       5, 5, 4, 4, 9, 3, 2, 3, 6, 0, 2, 0, 4, 6, 1, 8, 5, 5, 2, 3, 1, 3,
       2, 6, 5, 8, 9, 6, 0, 4, 6, 5, 1, 6, 6, 6, 2, 3, 1, 2, 9, 9, 4, 6,
       1, 5, 0, 9, 9, 8, 4, 7, 7, 5, 0, 0, 4, 9, 5, 4, 1, 9, 0, 0, 5, 6,
       5, 7, 3, 5, 3, 1, 5, 9, 2, 3, 9, 7, 4, 0, 0, 9, 2, 7, 3, 1, 4, 9,
       3, 8, 2, 5, 1, 1, 6, 9, 4, 3, 7, 1, 8, 1, 9, 7, 9, 0, 3, 2, 7, 7,
       2, 4, 0, 8, 4, 8, 5, 7, 2, 4, 2, 9, 5, 9, 5, 4, 4, 2, 0, 3, 3, 7,
       2, 5, 1, 5, 1, 0, 6, 7, 7, 3, 2, 3, 1, 0, 7, 3, 0, 7, 4, 9, 2, 5,
       3, 0, 0, 9, 5, 1, 7, 6, 5, 3, 4, 6, 0, 6, 6, 3, 4, 6, 2, 1, 6, 9,
       7, 4, 3, 4, 2, 4, 8, 0, 3, 1, 2, 4, 7, 2, 0, 8, 8, 6, 1, 8, 4, 5,
       1, 0, 2, 8, 4, 2, 0, 1, 6, 8, 8, 5, 8, 3, 1, 9, 0, 4, 6, 2, 9, 6,
       7, 1, 0, 4, 6, 0, 8, 2, 8, 9, 1, 2, 3, 9, 4, 7, 5, 7, 2, 9, 4, 6,
       2, 8, 7, 5, 8, 8, 0, 3, 2, 3, 1, 2, 6, 8, 5, 2, 8, 3, 1, 3, 0, 5,
       3, 1, 7, 2, 0, 1, 0, 9, 7, 9, 2, 3, 5, 3, 0,

In [75]:
X_shuffle,y_shuffle=shuffle(X,y,random_state=42,)
X_train,X_train,y_test,y_test=train_test_split(X_shuffle,y_shuffle,random_state=42,test_size=0.3,stratify=y)

In [76]:
cross_val_score(LogisticRegression(),X_shuffle,y_shuffle,cv=5,n_jobs=-1)

array([0.96703297, 0.95303867, 0.95264624, 0.96078431, 0.94084507])

In [77]:
np.mean(cross_val_score(KNeighborsClassifier(),X_shuffle,y_shuffle,cv=11,n_jobs=-1))

0.9865887204665605

In [124]:
model.intercept_

array([-0.02198477, -2.87761715, -0.03943244, -0.34707449,  0.01365265,
       -0.11334085, -0.08446892, -0.02547306, -2.82084043, -1.40333969])

In [125]:
model.coef_

array([[ 0.00000000e+00, -4.61488266e-02, -4.21745730e-02,
         4.18852519e-02, -9.41324684e-02, -3.76048904e-01,
        -2.69221731e-01, -2.95125758e-02, -1.27476272e-05,
        -1.18056991e-01, -1.16024797e-02,  1.73758675e-01,
         2.14618620e-01,  2.81038906e-01, -4.17673684e-03,
        -3.25076595e-02, -4.78277698e-03,  9.41829771e-02,
         2.16248286e-01, -6.55831067e-02, -3.80995272e-01,
         3.13868351e-01, -1.51719670e-02, -1.34085076e-02,
        -2.38982362e-03,  3.05036337e-02, -7.63426418e-02,
        -1.68203722e-01, -6.43030748e-01,  3.33508155e-02,
         4.03148961e-02, -1.54133606e-04,  0.00000000e+00,
         2.59834202e-01,  1.56328474e-01, -1.36847004e-01,
        -6.36512808e-01, -5.78812342e-02, -5.80958536e-02,
         0.00000000e+00, -1.72569373e-03, -2.67490030e-02,
         2.25330904e-01, -3.03498381e-01, -2.92844682e-01,
         3.23904839e-03,  1.36460738e-01, -8.98661242e-05,
        -1.20123721e-03, -1.32347270e-01,  2.67496690e-0

In [126]:
model.predict_proba(X_test)

array([[6.79394161e-17, 9.98834004e-01, 1.72453618e-07, ...,
        4.00402205e-27, 6.56622874e-04, 1.75964972e-07],
       [1.57384066e-09, 1.34654613e-03, 2.04096533e-03, ...,
        4.39811858e-04, 3.19333166e-05, 1.17124076e-06],
       [7.72047147e-15, 7.89570349e-01, 4.78856937e-10, ...,
        5.28346452e-09, 2.10371393e-01, 1.44379474e-09],
       ...,
       [3.98498422e-11, 7.42752899e-04, 2.24412907e-07, ...,
        8.65752703e-17, 7.47509492e-03, 1.67534473e-15],
       [6.57031954e-08, 9.39579923e-01, 2.74522482e-07, ...,
        5.49565318e-14, 5.45591828e-02, 5.84280978e-03],
       [1.61016185e-17, 9.52587876e-01, 3.13808392e-02, ...,
        1.83227595e-27, 1.26589191e-02, 2.34455421e-08]])

In [127]:
model.predict_proba(y_test)

ValueError: Expected 2D array, got 1D array instead:
array=[1 3 1 5 0 6 6 7 4 9 3 9 7 7 6 1 5 7 3 3 9 8 5 5 4 4 9 3 2 3 6 0 2 0 4 6 1
 8 5 5 2 3 1 3 2 6 5 8 9 6 0 4 6 5 1 6 6 6 2 3 1 2 9 9 4 6 1 5 0 9 9 8 4 7
 7 5 0 0 4 9 5 4 1 9 0 0 5 6 5 7 3 5 3 1 5 9 2 3 9 7 4 0 0 9 2 7 3 1 4 9 3
 8 2 5 1 1 6 9 4 3 7 1 8 1 9 7 9 0 3 2 7 7 2 4 0 8 4 8 5 7 2 4 2 9 5 9 5 4
 4 2 0 3 3 7 2 5 1 5 1 0 6 7 7 3 2 3 1 0 7 3 0 7 4 9 2 5 3 0 0 9 5 1 7 6 5
 3 4 6 0 6 6 3 4 6 2 1 6 9 7 4 3 4 2 4 8 0 3 1 2 4 7 2 0 8 8 6 1 8 4 5 1 0
 2 8 4 2 0 1 6 8 8 5 8 3 1 9 0 4 6 2 9 6 7 1 0 4 6 0 8 2 8 9 1 2 3 9 4 7 5
 7 2 9 4 6 2 8 7 5 8 8 0 3 2 3 1 2 6 8 5 2 8 3 1 3 0 5 3 1 7 2 0 1 0 9 7 9
 2 3 5 3 0 2 9 1 6 1 9 5 5 5 4 7 7 9 3 6 9 4 6 1 8 5 3 7 0 2 2 6 4 8 7 9 2
 0 8 4 6 7 3 1 5 4 7 2 4 9 4 2 1 4 7 1 7 2 9 2 6 7 3 7 3 2 9 9 8 8 9 4 1 7
 9 4 8 9 8 8 0 1 3 0 0 0 9 6 8 4 7 0 7 3 1 8 5 7 0 9 5 0 6 9 4 7 5 6 1 5 3
 4 6 5 1 6 8 7 0 8 3 6 5 0 3 2 3 5 6 4 5 2 8 6 4 1 8 6 6 2 5 4 8 9 1 7 3 2
 3 4 7 1 1 4 8 8 6 2 3 6 1 7 8 8 4 0 6 8 5 2 3 2 9 0 5 0 4 7 1 5 0 2 6 0 0
 3 1 8 6 7 7 6 5 0 1 8 3 8 9 9 5 7 8 3 9 7 3 8 6 5 5 5 2 9 8 0 9 0 4 7 1 8
 0 4 2 9 1 0 4 6 3 1 6 5 4 5 8 8 2 7 9 6 1 1].
Reshape your data either using array.reshape(-1, 1) if your data has a single feature or array.reshape(1, -1) if it contains a single sample.

In [131]:
model.predict(y_test)

ValueError: Expected 2D array, got 1D array instead:
array=[1 3 1 5 0 6 6 7 4 9 3 9 7 7 6 1 5 7 3 3 9 8 5 5 4 4 9 3 2 3 6 0 2 0 4 6 1
 8 5 5 2 3 1 3 2 6 5 8 9 6 0 4 6 5 1 6 6 6 2 3 1 2 9 9 4 6 1 5 0 9 9 8 4 7
 7 5 0 0 4 9 5 4 1 9 0 0 5 6 5 7 3 5 3 1 5 9 2 3 9 7 4 0 0 9 2 7 3 1 4 9 3
 8 2 5 1 1 6 9 4 3 7 1 8 1 9 7 9 0 3 2 7 7 2 4 0 8 4 8 5 7 2 4 2 9 5 9 5 4
 4 2 0 3 3 7 2 5 1 5 1 0 6 7 7 3 2 3 1 0 7 3 0 7 4 9 2 5 3 0 0 9 5 1 7 6 5
 3 4 6 0 6 6 3 4 6 2 1 6 9 7 4 3 4 2 4 8 0 3 1 2 4 7 2 0 8 8 6 1 8 4 5 1 0
 2 8 4 2 0 1 6 8 8 5 8 3 1 9 0 4 6 2 9 6 7 1 0 4 6 0 8 2 8 9 1 2 3 9 4 7 5
 7 2 9 4 6 2 8 7 5 8 8 0 3 2 3 1 2 6 8 5 2 8 3 1 3 0 5 3 1 7 2 0 1 0 9 7 9
 2 3 5 3 0 2 9 1 6 1 9 5 5 5 4 7 7 9 3 6 9 4 6 1 8 5 3 7 0 2 2 6 4 8 7 9 2
 0 8 4 6 7 3 1 5 4 7 2 4 9 4 2 1 4 7 1 7 2 9 2 6 7 3 7 3 2 9 9 8 8 9 4 1 7
 9 4 8 9 8 8 0 1 3 0 0 0 9 6 8 4 7 0 7 3 1 8 5 7 0 9 5 0 6 9 4 7 5 6 1 5 3
 4 6 5 1 6 8 7 0 8 3 6 5 0 3 2 3 5 6 4 5 2 8 6 4 1 8 6 6 2 5 4 8 9 1 7 3 2
 3 4 7 1 1 4 8 8 6 2 3 6 1 7 8 8 4 0 6 8 5 2 3 2 9 0 5 0 4 7 1 5 0 2 6 0 0
 3 1 8 6 7 7 6 5 0 1 8 3 8 9 9 5 7 8 3 9 7 3 8 6 5 5 5 2 9 8 0 9 0 4 7 1 8
 0 4 2 9 1 0 4 6 3 1 6 5 4 5 8 8 2 7 9 6 1 1].
Reshape your data either using array.reshape(-1, 1) if your data has a single feature or array.reshape(1, -1) if it contains a single sample.